### PR TITLE
localhost.yml

### PR DESCRIPTION
**Pull request by makflwana**
---
- name: Install bearded-avenger
  hosts: localhost
  become: True
  roles:
    - { role: centos7, tags: role-centos7 }
    - { role: bearded-avenger, tags: role-bearded-avenger }
  post_tasks:
    - name: start cif-services
      command: systemctl start {{ item }}
      command: systemctl enable {{ item }}
      with_items:
        - cif-router
        - cif-httpd
        - csirtg-smrt

### CODE REVIEW

**Comment by wesyoung** [comment]
woa, think you merged from the wrong branch? :)

**Comment by makflwana** [comment]
Did I ? Holy moly!!!

**Comment by wesyoung** [comment]
you should try forking the repo and creating a pr from your own branch of master..

**Comment by makflwana** [comment]
Cool I did the as for bearded avenger

**Pull request closed without merging**
