### PR TITLE
Ubuntu 16.04

### PR DESCRIPTION
**Pull request by tk-hendrik**
Hi,
spent some time to get the build & install routines ready for Ubuntu 16.04.

Installer works so far with & without elasticsearch store.

`make test`
```
py.test --cov=cif
====================================================== test session starts ======================================================
platform linux2 -- Python 2.7.12, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/10461771/contrib/bearded-avenger, inifile: 
plugins: cov-2.4.0
collected 17 items 

test/test_gatherer_asn.py .
test/test_gatherer_geo.py .
test/test_gatherer_peer.py .
test/test_httpd.py .....
test/test_hunter.py .
test/test_peers.py .
test/test_router.py .
test/test_storage_elasticsearch.py ss
test/test_storage_rdflib.py .
test/test_store.py ..
test/zadvanced/test_hunter.py s

---------- coverage: platform linux2, python 2.7.12-final-0 ----------
Name                                    Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------
cif/__init__.py                             3      0      0      0   100%
cif/gatherer/__init__.py                   71     53     12      0    22%
cif/gatherer/asn.py                        39      7     10      4    73%
cif/gatherer/peers.py                      26      0     10      3    92%
cif/httpd/__init__.py                     261    153     82     12    39%
cif/httpd/common.py                        37      7     21      6    78%
cif/httpd/feed/__init__.py                 14      4      6      1    55%
cif/httpd/feed/email.py                    21     16     12      0    15%
cif/httpd/feed/fqdn.py                     23      2     12      3    86%
cif/httpd/feed/ipv4.py                     46     34     22      0    18%
cif/httpd/feed/ipv6.py                     23     15     10      0    24%
cif/httpd/feed/url.py                      18     14     12      0    13%
cif/hunter/__init__.py                     67     39     12      0    35%
cif/store/__init__.py                     206    128     48      3    34%
cif/store/sqlite/__init__.py               44      3      4      1    88%
cif/store/sqlite/indicator.py             273     40     96     31    80%
cif/store/sqlite/ip.py                     32      6      4      1    81%
cif/store/sqlite/message.py                11     11      0      0     0%
cif/store/sqlite/tag.py                    11     11      0      0     0%
cif/store/sqlite/token.py                 137     61     60     12    47%
cif/store/zelasticsearch/__init__.py       20     20      4      0     0%
cif/store/zelasticsearch/indicator.py     217    217     80      0     0%
cif/store/zelasticsearch/token.py         125    125     40      0     0%
cif/store/zrdflib.py                       66     14     10      1    80%
cif/utils.py                               25      8      8      0    58%
-------------------------------------------------------------------------
TOTAL                                    1816    988    575     78    41%


============================================= 14 passed, 3 skipped in 1.25 seconds ==============================================

```

Known problems:
As assumed some open problems with systemd - will dive deeper into it the next days, hopefully.

Any suggestions for this PR?
Regards,
Hendrik

### CODE REVIEW

**Comment by wesyoung** [comment]
seems sane. systemd was the same thing i was thinking about, if you check out the centos72 deployment you'll see how i solved it for centos, i'm guessing those configs should look similar (eg: get rid of the initd stuff, etc). there were some issues with vagrant blocking my initial testing, just hadn't had a chance to circle around back..

normally i just hit the merge button, but based on your msg, should i wait till you work through the systemd stuff? this is related to #63 fwiw.

**Comment by tk-hendrik** [comment]
Hi Wes,
thanks for the hint to the centos files - I've adjust them a little bit to get the defaults running again. 

Maybe you want to adapt following change for Centos?
```
-EnvironmentFile=-/etc/cif.env
+EnvironmentFile=-/etc/default/cif
```
Hint: The dash means 'optional' for systemd. So it won't complain about non-existing files.
Question: I just assume your thought "cif.env" File would be the same as the old `/etc/default/cif`. Am I right?

It's not ready yet, cause I'm missing my logfiles after changing to the unit files - any hints where they might be?

**Comment by tk-hendrik** [comment]
>  Question: I just assume your thought "cif.env" File would be the same as the old /etc/default/cif. Am I right?
Drop that question - found my glasses and your template :)

**Comment by wesyoung** [comment]
ack, will look at the centos bits. first real exposure to systemd, so i'm sure i'm missing stuff in places. as far as logs go; in centos i had to resort to using:

https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

something like (off the top of my head):

```
$ journalctl -u cif-router.service -f
```

nothing was, by default in the normal "/var/log/cif.." places.. the same might go for ubuntu16 ?

let me know if this makes sense and solves your problem. then we'll merge...

**Comment by tk-hendrik** [comment]
journalctl shows the logs as expected. But imho keeping those logs away from systemd smells better. But maybe I'm just old-fashioned...

**Comment by tk-hendrik** [comment]
Last but not least: Those unit files are working even if there aren't any application based logs within `/var/log/cif/*` - tweaks on the logger would be off-topic to this pull request.

IMO this PR ma be done - feel free to merge if you wish.

OT: There are some other things I found during playing with bearded-avenger - if nothing against it, i would open some issues to track those thoughts. OK?

**Comment by wesyoung** [comment]
go for it; this is the model we use [if you're not familiar with the ZMQ community]:

https://rfc.zeromq.org/spec:42/C4

so be sure to list them as discrete problems with an idea about the solution. makes it easier to discuss in context [and easier to merge]. you'll note that not all the existing issues follow that logic, but i'm wrapping around to fix that problem...

**Comment by wesyoung** [comment]
ty!

**Comment by wesyoung** [comment]
(also, i posted a note about the PR to the mailing list [in case you're not on it]. gave you kudos!)

**Pull request merged**
